### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dmarrazzo** [timbertson/gnome-shell-scroll-workspaces#13]
It simple does not work in my F22/64bit.
Can I provide some traces?

**Comment by gfxmonk** [comment]
Yeah, I'll need some error logs to do anything about this. Does gnome-shell actually load the extension? (it might not be compatible with F22 yet, I haven't tried)

**Comment by jonnius** [comment]
Where to find the logs?

**Comment by timbertson** [comment]
Closing in favour of the more descriptive #29.
