### ISSUE TITLE
Update on https://extensions.gnome.org/

### ISSUE THREAD

**Issue by Wulf** [timbertson/gnome-shell-scroll-workspaces#21]
@timbertson The repo is up to date (yay!), but the version uploaded to https://extensions.gnome.org/ needs to be updated too!

**Comment by timbertson** [comment]
I updated a couple of days ago, can you double check? (https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/ )

![screenshot from 2016-04-15 21-09-51](https://cloud.githubusercontent.com/assets/14172/14559825/c97ac166-034e-11e6-9622-0b89583134c0.png)

**Comment by Wulf** [comment]
It's perfect. I probably did something wrong last time. 
Thanks Tim :)
