### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ba1020** [timbertson/gnome-shell-scroll-workspaces#23]
or i don't get it - how to use it.

so i move the mouse over the top panel and than I scroll with the wheel - and nothing happens

**Comment by timbertson** [comment]
That should be it. It may not be running - maybe look for extension errors? You can press alt+f2, type `lg` (for "looking glass") and check the "Extensions" tab - check if this extension is present and whether there are any errors.

**Comment by ba1020** [comment]
your right - the extension is not running - there seems to be a problem with starting it

**Comment by timbertson** [comment]
reopen if you have more information
