### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by CromFr** [timbertson/gnome-shell-scroll-workspaces#24]
The makefile has references to 0inst folder

https://github.com/timbertson/gnome-shell-scroll-workspaces/blob/master/Makefile#L1

Also it would be great to have some build instructions in the readme

**Comment by timbertson** [comment]
Apologies, the build process in this project is a bit old and crufty. I hope de058d5afb10694c18de3f12cf6c9b51c98605cb clears things up? Let me know if you still find anything missing.
