### ISSUE TITLE
Make it work on Gnome 3.22

### ISSUE THREAD

**Issue by hekri-d** [timbertson/gnome-shell-scroll-workspaces#25]
It'd be nice if you could make it work on Gnome 3.22. At the moment it doesn't even install for me on Gnome 3.22.2 on top of Antergos.

**Comment by ai** [comment]
I have same problem :(

**Comment by hekri-d** [comment]
Hi ai (and others).

I managed to get it to work but, at the time, I was setting up my new Arch machine and I forgot to get back here and post the solution. I note stuff with which I have problems for later so I'm just gonna copy/paste (unedited) what I noted back then because I don't have that much time right now. 

These notes were meant as a reference for personal use so but if you have a bit experience with extensions (and linux overall) you should be able to decipher them.

_Extension error: 'can't find file something...' (file missing in extension dir. - renamed(?))_
_1)downloaded the extension from github, moved it to  Desktop and extracted it_
_2)cd to the directory created after extraction_
_3)ran ./tools/gup_

_4)manually installed the extension from gnome's tweak-tool using the zip file downloaded (logged out and _back in. Tweak tool shows extension but it doesn't work)_
_5)the extension was installed in ~./local/share/gnome-shell/extensions_

_6)cd into the previously extracted dir. (Desktop) and into ../scroll-workspaces/schemas_
_7)from there copied 'gschemas.compiled' and pasted it into the schemas dir of the scroll-workspaces dir._  _extension (./local/extensions/...)_
_8)logged out and back in and it works._

There's a cleaner way to do this and I'll post it here later if the extension is not already fixed to work with gnome 3.22.

A big thanks to the developers/mainainers.

**Comment by ai** [comment]
So wehave a problems with `gschemas.compiled`? @timbertson do you have idea how to gis it or you need extra data from you broken machines? :D (I used Fedora and found this issue with few other extensions)

**Comment by smichel17** [comment]
I was able to make it work just by:

- Get repo (either clone or download zip and extract)
- cd into repo
- `./tools/gup`
- `./tools/gup zip`
- Open tweak tool, 'extensions' tab, install shell extension from folder, select the zip file you just made.
- Log out, log in
- Extension works

**Comment by timbertson** [comment]
Hmm.. The compiled schemas aren't checked in, so it makes sense that you'd have to build them if you checkout from git (although I've just added them, since I think they should be pretty stable now).

But they should have already been in the ZIP. Can someone check that `schemas/gschemas.compiled` is in the ZIP they got from extensions.gnome.org? I can't actually find the download link, so all I have is the latest version (which does have that file)
