### ISSUE TITLE
Scroll doesn't work on the Gnome 16.04.02

### ISSUE THREAD

**Issue by Aleksandaar** [timbertson/gnome-shell-scroll-workspaces#29]
When scrolling, the workspace indicator shows up (I have checked that option just to see if the scroll is being registered), but the workspace is not changed to the next one.
Tested on clean installation of Gnome 3 (Ubuntu LTS 16.04.02)

**Comment by jonnius** [comment]
Same here on Ubuntu 18.10 with GNOME Shell 3.30.1. May be related to #13? Where do we find the logs from the extension?

**Comment by timbertson** [comment]
Logs should be in `~/.cache/gdm/session.log`, according to https://wiki.gnome.org/Projects/GnomeShell/LookingGlass

**Comment by timbertson** [comment]
Closing as stale, reopen if you have more info :)
