### ISSUE TITLE
Not working with gnome-shell 3.30

### ISSUE THREAD

**Issue by yrro** [timbertson/gnome-shell-scroll-workspaces#31]
Rolling the scroll wheel causes gnome-shell to log the following:

```
Sep 06 10:59:20 gnome-shell[1707]: JS ERROR: TypeError: global.screen is undefined
                                   Ext.prototype._onScrollEvent@/home/sam/.local/share/gnome-shell/extensions/scroll-workspaces@gfxmonk.net/extension.js:108:7
```

**Comment by yrro** [comment]
I think the extension was broken by https://gitlab.gnome.org/GNOME/gnome-shell/commit/47ea10b7c976abb1b9ab4f34da87abb1e36855fe

I think changing `global.screen` to `global.workspace_manager` will make things work again.

**Comment by timbertson** [comment]
Thanks, f44ede1794d6143768fbbfc3e51ff284172b5820 should fix it though I've not tested locally.
