### ISSUE TITLE
Doesn't work on 3.30@Archlinux

### ISSUE THREAD

**Issue by Confucij** [timbertson/gnome-shell-scroll-workspaces#33]
Extension stops working after update to 3.30 on Archlinux

**Comment by 873314461** [comment]
I have the same problem.

**Comment by timbertson** [comment]
The last commit (https://github.com/timbertson/gnome-shell-scroll-workspaces/commit/733f41f572cdd04ac478d80b3ab5b0f766470cc7) should have fixed that already, it's still waiting for a review on extensions.gnome.org though. Please reopen if it's still broken on the latest commit.
