### ISSUE TITLE
Not working since newer version and GNOME 3.28

### ISSUE THREAD

**Issue by hyphone** [timbertson/gnome-shell-scroll-workspaces#34]
Hello and good day,

this is what I got since the newest update from extensions.gnome.org:

`JS ERROR: TypeError: this._workspaceManager is undefined
                                               Ext.prototype._onScrollEvent@/home/krst/.local/share/gnome-shell/extensions/scroll-workspaces@gfxmonk.net/extension.js:109:7`

Seems like the update was stricktly for 3.30 - the previous version from extensions.gnome.org works.
So I don't know if it's a really a bug. Perhaps we can suggest that extensions for newer GNOME versions shouldn't be able to be installed in the first place.

**Comment by timbertson** [comment]
Can you tell which version you've got? Extensions.gnome.org shouldn't let you install v18 on anything less than gnome-shell 3.30. See attached, v18 is a clean break which only supports shell v3.30:

![screenshot from 2018-09-26 20-58-43](https://user-images.githubusercontent.com/14172/46075863-2c465d00-c1cf-11e8-96f9-1ebe45cf3a39.png)

Maybe their version restrictions don't work properly on minor versions, but that sounds surprising.

**Comment by timbertson** [comment]
You can look in metadata.json of your installed extension to verify which shell versions it supports. If you're running <3.30 yet have a metadata.json which supports only 3.30, then it sounds like that the website gave you that version.

**Comment by sojusnik** [comment]
Same here under Gnome 3.28 with Ubuntu 18.04.
Although I installed v16 manually (downloaded it and replaced all files in `/home/user/.local/share/gnome-shell/extensions/scroll-workspaces@gfxmonk.net`, the extension website wants to update it to v18, which won't work anymore.

**Comment by timbertson** [comment]
I've posted on the gnome issue tracker, since it looks like this is a bug in extensions.gnome.org: https://gitlab.gnome.org/Infrastructure/Websites/issues/273

**Comment by Rmano** [comment]
I'm seeing the same problem here, on Ubuntu 18.04/ Gnome shell 3.28.2. Could be that in the list above there is no explicit version for shell 3.28? (still a bug, but...)

**Comment by timbertson** [comment]
Good point. I've uploaded a version tagged explicitly with 3.26 and 3.28, I'll shout out when it's reviewed and ready for someone to try out. Hopefully users on 3.30 don't start getting this version!

**Comment by sojusnik** [comment]
The newly uploaded version finally works with Gnome 3.28 on Ubuntu 18.04. Thanks!

**Comment by timbertson** [comment]
Yay :) :tada:
