### ISSUE TITLE
Feature Request: Horizontal scroll

### ISSUE THREAD

**Issue by JREAM** [timbertson/gnome-shell-scroll-workspaces#35]
Love the plugin! 

**Feature Request:** Would be awesome to have a switch for Horizontal Scroll -- Using the Workspace Grid I prefer horizontal Workspaces versus Vertical. It DOES work with a MX Master mouse side scroll wheel, but not many have this on their mouse!

Thanks for the plugin!

**Comment by The-Humble-Fool** [comment]
Latest Gnome now has horizontal workspaces feature and unfortunately this extension does not support horizontal scrolling. Requesting to add support for horizontal scrolling too.

**Comment by job1925** [comment]
Shouldn't this be closed because of #45 ?
