### ISSUE TITLE
Not working on Fedora 29 with Wayland

### ISSUE THREAD

**Issue by hyphone** [timbertson/gnome-shell-scroll-workspaces#36]
Hello and good day,

on Fedora 29 and Gnome 3.30.1 on Wayland I get this Error:

`gnome-shell[1930]: JS ERROR: TypeError: global.screen is undefined
JS ERROR: TypeError: global.screen is undefined
                                                         _onScrollEvent@/home/krst/.local/share/gnome-shell/extensions/scroll-workspaces@gfxmonk.net/extension.js:108:7`

This is with version 18 from extensions.gnome.org

Edit: using Wayland

Xorg works

Edit2: after a reboot it works (?) - I keep an eye on it

**Comment by timbertson** [comment]
It's been reported and seems to be fixed already (#31 #32 #33), possibly you had an old version and got updated to the right version when you rebooted?
